# Generated by Django 4.2.2 on 2023-06-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customtable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('passwords', models.CharField(max_length=255)),
                ('Roles', models.CharField(max_length=255)),
                ('creatby', models.IntegerField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updatedby', models.IntegerField(blank=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
