# Generated by Django 4.2.2 on 2023-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GodView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=255)),
                ('Start', models.DateTimeField()),
                ('Expire', models.IntegerField()),
                ('ip', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Custom_token',
                'managed': False,
            },
        ),
    ]
