# Generated by Django 4.2.2 on 2023-06-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0002_godview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GodView',
        ),
    ]
